### ISSUE TITLE
Midgame cutscenes crash game

### ISSUE THREAD

**Issue by thobbsinteractive** [thobbsinteractive/magic-carpet-2-community-patch#22]
After completing level 5, and completing the secret level the game crashed playing one of the mid-game cut-scenes in sub_1B280_run_intro_events()

**Comment by GrimSqueaker** [comment]
I looked into it after level 14 (?, CUT3.DAT) and this is the culprit:
```
PlayInfoFmv(0, 1, 0/*ONLY HACK*/, cutScenePath);//FIXME
```
I'm not sure if I can fix this.

**Comment by thobbsinteractive** [comment]
I think it was after level 5 my crash happened, but I'll take a look at
some point after I've finished the resolution changes, so likely sometime
next week.

**Comment by thobbsinteractive** [comment]
This seems to be working now.
